[package]
name = "littlewing_web"
version = "0.1.0"
authors = ["Florian Lackner <florian.lackner@gmail.com>"]
edition = "2018"

[dependencies]
js-sys = "0.2.7"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]